# AgenticART Unified Curriculum v4.0 - Praxis Architecture
# ============================================================================
# V1 (Execution) is now the VERIFICATION LAYER within V2 (Reasoning)
#
# Philosophy:
#   - V2 provides the HYPOTHESIS: The agent reasons about a vulnerability
#   - V1 provides the VERIFICATION: Binary ground truth via tool execution
#   - Calibration detects HALLUCINATION: High confidence + Failed execution
#
# This generates the highest-quality DPO training signals:
#   - CHOSEN: True understanding (confident + verified)
#   - REJECTED: Hallucination (confident + failed verification)
# ============================================================================

version: "4.0"
name: "AgenticART Praxis Curriculum"

# ============================================================================
# METADATA
# ============================================================================

metadata:
  total_challenges: 31        # V2 reasoning challenges (V1 embedded as verification)
  verification_tasks: 33      # V1 tasks (now embedded in V2 challenges)
  belt_levels: 8
  estimated_training_samples: 5000  # Higher quality with calibration signals
  architecture: "praxis"      # V1 nested within V2

# ============================================================================
# STAGE DEFINITIONS (V2 Reasoning with Embedded Verification Tasks)
# ============================================================================
# Verification tasks are now embedded directly in V2 challenge YAML files.
# See v2/pillars/*/challenges.yaml for the consolidated format.

stages:
  # --------------------------------------------------------------------------
  # WHITE BELT: Observation & Pattern Recognition
  # --------------------------------------------------------------------------

  - stage: 1
    name: "Observation Discipline"
    phase: "security_reasoning"
    belt: "white"
    source: "v2"

    description: |
      Learn to observe systematically before forming conclusions.
      Identify security-relevant patterns without jumping to conclusions.

      VERIFICATION: V1 tool commands validate your observations against
      real device state.

    skills_gained:
      - "Structured observation process"
      - "Security-relevant pattern recognition"
      - "Distinguishing secure from insecure patterns"
      - "Basic vulnerability classification"
      - "Tool execution for verification"

    challenges:
      - method_observe_white_001
      - static_basic_white_001
      - neg_secure_white_001
      - neg_secure_white_002
      - taxonomy_basic_white_001

    prerequisites: []
    unlocks: [2]

  # --------------------------------------------------------------------------
  # YELLOW BELT: Hypothesis Formation
  # --------------------------------------------------------------------------

  - stage: 2
    name: "Hypothesis Formation"
    phase: "security_reasoning"
    belt: "yellow"
    source: "v2"

    description: |
      Form testable security hypotheses. Learn to trace data flows,
      classify vulnerabilities, and propose verification approaches.

      VERIFICATION: V1 commands test your hypotheses against live apps.

    skills_gained:
      - "Hypothesis construction"
      - "Data flow tracing"
      - "OWASP Mobile classification"
      - "Pattern recognition across similar code"
      - "Verification test design"

    challenges:
      - method_hypothesis_yellow_001
      - static_dataflow_yellow_001
      - neg_compare_yellow_001
      - taxonomy_owasp_yellow_001
      - transfer_api_yellow_001

    prerequisites: [1]
    unlocks: [3]

  # --------------------------------------------------------------------------
  # ORANGE BELT: Verification Design
  # --------------------------------------------------------------------------

  - stage: 3
    name: "Verification Design"
    phase: "security_reasoning"
    belt: "orange"
    source: "v2"

    description: |
      Design and execute tests to verify hypotheses. Handle ambiguous
      cases and subtle security issues.

      VERIFICATION: Complex V1 operations (SQLite, file access, network)
      provide ground truth for your analysis.

    skills_gained:
      - "Test plan design"
      - "Cross-function analysis"
      - "Subtle vulnerability detection"
      - "Ambiguous classification handling"
      - "Cross-domain pattern application"

    challenges:
      - method_test_orange_001
      - static_crossfunc_orange_001
      - neg_subtle_orange_001
      - taxonomy_ambiguous_orange_001
      - transfer_domain_orange_001

    prerequisites: [2]
    unlocks: [4]

  # --------------------------------------------------------------------------
  # GREEN BELT: Systematic Analysis
  # --------------------------------------------------------------------------

  - stage: 4
    name: "Systematic Analysis"
    phase: "security_reasoning"
    belt: "green"
    source: "v2"

    description: |
      Prioritize findings, analyze components systematically,
      and understand vulnerability chains.

    skills_gained:
      - "Finding prioritization"
      - "Component-level analysis"
      - "Vulnerability chain understanding"
      - "Patch analysis basics"

    challenges:
      - method_prioritize_green_001
      - static_component_green_001
      - taxonomy_chain_green_001
      - patch_basic_green_001

    prerequisites: [3]
    unlocks: [5]

  # --------------------------------------------------------------------------
  # BLUE BELT: Deep Understanding
  # --------------------------------------------------------------------------

  - stage: 5
    name: "Deep Understanding"
    phase: "security_reasoning"
    belt: "blue"
    source: "v2"

    description: |
      Understand fundamental security principles, analyze cryptographic
      implementations, and identify root causes.

    skills_gained:
      - "Negative case handling"
      - "Cryptographic vulnerability analysis"
      - "Novel vulnerability classification"
      - "Root cause identification"
      - "Platform-specific pattern transfer"
      - "Complex patch analysis"

    challenges:
      - method_negative_blue_001
      - static_crypto_blue_001
      - taxonomy_novel_blue_001
      - root_fund_blue_001
      - root_fund_blue_002
      - transfer_platform_blue_001
      - patch_complex_blue_001

    prerequisites: [4]
    unlocks: [6]

  # --------------------------------------------------------------------------
  # PURPLE BELT: Expert Calibration
  # --------------------------------------------------------------------------

  - stage: 6
    name: "Expert Calibration"
    phase: "security_reasoning"
    belt: "purple"
    source: "v2"

    description: |
      Avoid false positives, handle edge cases, and demonstrate
      expert-level pattern generalization.

      CRITICAL: At this level, calibration errors are heavily penalized.
      Your confidence MUST match your verification success rate.

    skills_gained:
      - "False positive avoidance"
      - "Holdout pattern recognition"
      - "Expert-level calibration"
      - "Epistemic humility"

    challenges:
      - neg_fp_purple_001
      - transfer_holdout_purple_001

    prerequisites: [5]
    unlocks: [7]

  # --------------------------------------------------------------------------
  # BROWN BELT: Advanced Root Cause
  # --------------------------------------------------------------------------

  - stage: 7
    name: "Advanced Root Cause"
    phase: "security_reasoning"
    belt: "brown"
    source: "v2"

    description: |
      Analyze complex vulnerability chains and incomplete patches.
      Understand systemic security failures.

    skills_gained:
      - "Vulnerability chain analysis"
      - "Incomplete patch detection"
      - "Systemic failure understanding"

    challenges:
      - root_chain_brown_001
      - patch_incomplete_brown_001

    prerequisites: [6]
    unlocks: [8]

  # --------------------------------------------------------------------------
  # BLACK BELT: Novel Discovery
  # --------------------------------------------------------------------------

  - stage: 8
    name: "Novel Discovery"
    phase: "security_reasoning"
    belt: "black"
    source: "v2"

    description: |
      Discover novel vulnerabilities using all accumulated skills.
      The synthesis of reasoning and verification.

      At this level, you must:
      - Form original hypotheses about unseen code
      - Design verification approaches
      - Execute tools to confirm findings
      - Express CALIBRATED confidence

    skills_gained:
      - "Novel vulnerability discovery"
      - "Zero-day identification"
      - "Full security research workflow"
      - "Publication-ready analysis"

    challenges:
      - root_novel_black_001

    prerequisites: [7]
    unlocks: []

# ============================================================================
# CALIBRATION THRESHOLDS
# ============================================================================

calibration:
  # Thresholds for the Praxis Runner's is_hallucination() function

  profiles:
    strict:
      confidence_threshold: 0.85
      execution_threshold: 0.15
      description: "Fewer flags, higher precision. Use for final training."

    moderate:
      confidence_threshold: 0.70
      execution_threshold: 0.30
      description: "Balanced. Good for iterative development."

    loose:
      confidence_threshold: 0.60
      execution_threshold: 0.40
      description: "More flags, catches subtle overconfidence. Use for debugging."

  default_profile: "moderate"

# ============================================================================
# TRAINING DATA GENERATION
# ============================================================================

training:
  sft_format: "alpaca"

  dpo_generation:
    enabled: true
    source: "praxis_calibration"  # DPO pairs come from calibration results

    signal_priorities:
      - type: "hallucination"
        weight: 1.0
        description: "High confidence + failed verification (REJECTED)"
      - type: "true_understanding"
        weight: 0.8
        description: "High confidence + passed verification (CHOSEN)"
      - type: "under_calibrated"
        weight: 0.5
        description: "Low confidence + passed verification"
      - type: "appropriate_uncertainty"
        weight: 0.3
        description: "Low confidence + failed verification"

  # Training phases
  curriculum_learning:
    warmup: [1, 2]           # White + Yellow (foundation)
    core: [3, 4, 5]          # Orange + Green + Blue (main capability)
    advanced: [6, 7, 8]      # Purple + Brown + Black (expert refinement)

# ============================================================================
# EVALUATION CHECKPOINTS
# ============================================================================

evaluation:
  checkpoints:
    - after_stage: 2
      name: "Basic Reasoning Checkpoint"
      test_type: "hypothesis_quality"
      pass_threshold: 0.75
      max_hallucination_rate: 0.30
      description: "Verify model forms valid hypotheses"

    - after_stage: 5
      name: "Advanced Reasoning Checkpoint"
      test_type: "root_cause_analysis"
      pass_threshold: 0.70
      max_hallucination_rate: 0.20
      description: "Verify model understands root causes"

    - after_stage: 8
      name: "Full Praxis Checkpoint"
      test_type: "novel_discovery"
      pass_threshold: 0.60
      max_hallucination_rate: 0.10
      description: "Verify model can discover AND verify novel findings"

  # Key metric: Calibration Error should decrease through stages
  calibration_targets:
    stage_2: 0.25   # Allow 25% calibration error at Yellow
    stage_5: 0.15   # Tighten to 15% at Blue
    stage_8: 0.08   # Expert level: 8% max calibration error

# ============================================================================
# END OF CURRICULUM DEFINITION
# ============================================================================
# V1 execution tasks are now embedded as verification_tasks in V2 challenges.
# Total V1 tasks embedded: 33 (distributed across 31 V2 challenges)
